### PR TITLE
Generating and storing coverage for unit tests

### PR DESCRIPTION
**Pull request by uoboda-splunk**
- Generates coverae.json report for unit tests
- small entrypoint.sh refactor 

Tested with nginx branch https://github.com/splunk/splunk-add-on-for-nginx/tree/unit-tests-refactor

### CODE REVIEW

**Comment by bhargav-nariyani-crest** [comment]
> * Generates coverae.json report for unit tests
> * small entrypoint.sh refactor
> 
> Tested with nginx branch https://github.com/splunk/splunk-add-on-for-nginx/tree/unit-tests-refactor

@uoboda-splunk 
Since the impacts of making any changes to common repo is large to cause issues in 70 repos and block dev team,
We need to test this with multiple repos to ensure this doesn't break any executions.
This should include all TAs with unit tests
TA not having Unit Tests but only Conf  only TA
TA which is UCC 2.x
TA which is UCC 3.x
Any repo or combination of repos which has all test types covered. (KO, UI, Unit, Backend, modinput)

**Comment by uoboda-splunk** [comment]
@bhargav-nariyani-crest

> This should include all TAs with unit tests
I will add test branches

> TA not having Unit Tests but only Conf only TA
Is https://github.com/splunk/splunk-add-on-for-juniper good for that?

> Any repo or combination of repos which has all test types covered. (KO, UI, Unit, Backend, modinput)
For instance https://github.com/splunk/splunk-add-on-for-servicenow is repository with KO, UI, Unit and modinput tests. I don't see backend tests there. What kind of tests are `backend`? Which TA has it?

> TA which is UCC 2.x
> TA which is UCC 3.x
How can I find out which TAs are using UCC 2.x and UCC 3.x?

Do we have a table or other combined info about TAs and which tests they have implemented?

**Comment by uoboda-splunk** [comment]
Additional branches were created to ensure correctness of changes:

https://github.com/splunk/splunk-add-on-for-box/tree/test/coverage-for-unit-tests
https://github.com/splunk/splunk-add-on-for-infoblox/tree/test/coverage-for-unit-tests
https://github.com/splunk/splunk-add-on-for-juniper/tree/test/coverage-for-unit-tests

**Comment by bhargav-nariyani-crest** [comment]
@uoboda-splunk Can we close this as I believe this is no longer required?

**Comment by uoboda-splunk** [comment]
closing this one. Implementation moved to https://github.com/splunk/addonfactory-repository-template/pull/42

**Pull request closed without merging**
